required = [
    "k8s.io/code-generator/cmd/client-gen",
    "k8s.io/code-generator/cmd/deepcopy-gen",
    "k8s.io/code-generator/cmd/informer-gen",
    "k8s.io/code-generator/cmd/lister-gen",
    "k8s.io/code-generator/cmd/defaulter-gen"
]

[[override]]
    name = "k8s.io/apiextensions-apiserver"
    version = "kubernetes-1.10.2"

[[constraint]]
    name = "k8s.io/kubernetes"
    version = "=v1.10.2"

[[constraint]]
    name = "k8s.io/api"
    version = "kubernetes-1.10.2"

[[constraint]]
    name = "k8s.io/apimachinery"
    version = "kubernetes-1.10.2"

[[constraint]]
    name = "k8s.io/code-generator"
    version = "kubernetes-1.10.2"

[[constraint]]
    name = "k8s.io/client-go"
    version = "kubernetes-1.10.2"

