apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterName }}-redis
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  config-file: |-
    {{- if .Values.redis.config }}
{{ .Values.redis.config | indent 4 }}
    {{- else }}
{{ tuple "config/_redis-config.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
    {{- end -}}

{{- if ((.Values.redis.mode) and (eq .Values.redis.mode "replica") and (gt .Values.redis.members 2)) }}
  sentinel-config-file: |-
    {{- if .Values.sentinel.config }}
{{ .Values.sentinel.config | indent 4 }}
    {{- else }}
{{ tuple "config/_redis-sentinel-config.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
    {{- end -}}
{{- end -}}
