apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterName }}-redis
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
{{ include "server-configmap.data" . | indent 2 }}
