# Default values for redis-operator

# clusterScoped is whether redis-operator should manage kubernetes cluster wide redis clusters
# Also see rbac.create and controllerManager.serviceAccount
clusterScoped: true

# Also see clusterScoped and controllerManager.serviceAccount
rbac:
  create: true

# operatorImage is Redis Operator image
operatorImage: 127.0.0.1:5000/redis-operator:latest
imagePullPolicy: IfNotPresent

defaultStorageClassName: local-storage

controllerManager:
  # With rbac.create=false, the user is responsible for creating this account
  # With rbac.create=true, this service account will be created
  # Also see rbac.create and clusterScoped
  serviceAccount: redis-controller-manager
  logLevel: 2
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 150Mi
    requests:
      cpu: 80m
      memory: 50Mi
